site_name: Ansible Expo
site_author: Christopher Steel
nav:
    - Home: index.md
    - Development:
       - Overview: development/index.md
       - configuration: development/configuring-an-expo-development-system.md
       - ansible: development/ansible-project-setup.md
       - project development: development/project-development.md
    - Controller: 
       - venv: venv/installing-ansible-into-a-virtual-python-3-environment.md
       - sshkeys : sshkeys
    - Usage:
       - Maintenance Commnads: maintenance-command-examples.md
       - Adding New Systems:
           - System preparations: 
               - BIOS/(U)EFI Settings:
                   - Wake-on-LAN (Wol): bios/enabling-wol.md
                   - Network booting: bios/enabling-pxe.md
               - Hardware:
                   - Mirrored boot: mdadm/index.md
                   - Drive locations: chassis/index.md
               - DNS:
                   - DNS: dns/index.md
                   - /etc/hosts file: etc_hosts/index.md
           - Connectivity:
               - Connectivity test: ssh/testing-connectivity.md
               - ssh agent: ssh/sshagent.md
               - ssh-add: ssh/sshadd.md 
           - inventory/production/hosts:
               - Research Workstation example: inventory/workstation-example.md 
               - Storage Server example: inventory/server-example.yml

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tabs
  palette:
    primary: indigo
    accent: deep purple
  font:
    text: Roboto
    code: Roboto Mono
plugins:
  - search # necessary for search to work
  - minify:
      minify_html: true
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
